<a href="https://colab.research.google.com/github/lipsitasahu/lipsitasahu/blob/main/ad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

C:\Users\lipsita\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
df=pd.read_csv("advertisement.csv")

In [ ]:
'df.head()'

'df.head()'

In [ ]:
'df.shape'

'df.shape'

In [ ]:
'df.info'

'df.info'

In [ ]:
'df.describe()'

'df.describe()'

In [ ]:
'''import seaborn as sns
sns.boxplot(df['Daily Time Spent on Site'])'''

"import seaborn as sns\nsns.boxplot(df['Daily Time Spent on Site'])"

In [ ]:
'plt.hist(df.Age)'

'plt.hist(df.Age)'

In [ ]:
'df.columns'

'df.columns'

In [ ]:
'''col=['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage']
import matplotlib.pyplot as plt 
for i in col:
    sns.distplot(df[i])
    plt.show()'''

"col=['Daily Time Spent on Site', 'Age', 'Area Income',\n       'Daily Internet Usage']\nimport matplotlib.pyplot as plt \nfor i in col:\n    sns.distplot(df[i])\n    plt.show()"

In [ ]:
'''plt.style.use('ggplot') # Using ggplot2 style visuals 
f, ax = plt.subplots(figsize=(11, 15))
ax.set_facecolor('white') 
ax.set(xlim=(-10, 200)) 
plt.ylabel('Variables') 
plt.title("Overview Data Set") 
ax = sns.boxplot(data = df,   
                 orient = 'h',   
                 palette = 'Set2')'''

'plt.style.use(\'ggplot\') # Using ggplot2 style visuals \nf, ax = plt.subplots(figsize=(11, 15))\nax.set_facecolor(\'white\') \nax.set(xlim=(-10, 200)) \nplt.ylabel(\'Variables\') \nplt.title("Overview Data Set") \nax = sns.boxplot(data = df,   \n                 orient = \'h\',   \n                 palette = \'Set2\')'

In [ ]:
'''df.groupby('Male').size().plot(kind='pie',textprops={'fontsize':20},colors=['violet','lime'])'''

"df.groupby('Male').size().plot(kind='pie',textprops={'fontsize':20},colors=['violet','lime'])"

In [ ]:
'plt.figure(figsize=(8,8))' 
'sns.heatmap(df.corr(),annot = True)'

'sns.heatmap(df.corr(),annot = True)'

In [ ]:
'''plt.scatter(df['Daily Internet Usage'],df['Age'])'''

"plt.scatter(df['Daily Internet Usage'],df['Age'])"

In [ ]:
'''sns.regplot(df['Daily Internet Usage'],df['Age'],data=df)'''

"sns.regplot(df['Daily Internet Usage'],df['Age'],data=df)"

In [ ]:
# separating independent and dependent features 
X = df[['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage']] 
y = df['Clicked on Ad']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.4,random_state=1)

SyntaxError: invalid syntax (<ipython-input-63-ffc080aea254>, line 1)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model.fit(X_train,y_train)

C:\Users\lipsita\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
model.score(X_test,y_test)

0.8725

In [ ]:
from sklearn.metrics import accuracy_score 
accuracy_score(y_test,y_pred)

0.9075

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
y_pred

array([0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,

In [ ]:
y_test

993    0
859    0
298    0
553    1
672    0
      ..
81     0
159    1
333    0
837    1
474    1
Name: Clicked on Ad, Length: 400, dtype: int64

In [ ]:
from sklearn.metrics import confusion_matrix 
confusion_matrix(y_test,y_pred)

array([[202,  17],
       [ 20, 161]], dtype=int64)

In [ ]:
res=model.predict([[68.95,35,61833.90,256.09]])

In [ ]:
res

array([0], dtype=int64)