<a href="https://colab.research.google.com/github/lipsitasahu/lipsitasahu/blob/main/cloth_project_lipsita.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt   
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline 

C:\Users\lipsita\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
cloth_df=pd.read_csv("clothdataset.csv")

In [ ]:
cloth_df.head()

ImgID BodySize  WaistSize Gender  \
0                                  1_512        M         32      F   
1                             11-catalog       XL         40      M   
2    1613117687_1_JNX-ARDHNA-RIWAZ1-1008        M         32      F   
3  1613827564_1_RAJT-6824-RED_-PEACHMODE        M         32      F   
4                      182gw01-5934bk191        M         32      F   

  Complexion Occasion DressColor DressColor2 DressSize  DressDesign  \
0      Asian    Party     Orange        None         M  Half Sleeve   
1      Asian    Party       Blue        None        XL  Full Sleeve   
2      Asian    Party        Red        None         M  Half Sleeve   
3      Asian    Party        Red        None         M  Full Sleeve   
4      Asian    Party     Golden        None         M  Half Sleeve   

  DressCategory  Matching Percentage Matching  
0      Ethinic                    40        N  
1      Ethinic                    86        Y  
2      Ethinic                     6        N  
3      Ethinic                    68        Y  
4      Ethinic                    80        Y

In [ ]:
cloth_df.iloc[12:13]

ImgID BodySize  WaistSize Gender Complexion  \
12  502793f6035b09a01561bcf231817d24        M         34      M      White   

   Occasion DressColor DressColor2 DressSize  DressDesign DressCategory  \
12   Casual      Black        None         M  Half Sleeve       Western   

    Matching Percentage Matching  
12                   59        N

In [ ]:
cloth_df.shape

(111, 13)

In [ ]:
cloth_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   ImgID                111 non-null    object
 1   BodySize             111 non-null    object
 2   WaistSize            111 non-null    int64 
 3   Gender               111 non-null    object
 4   Complexion           111 non-null    object
 5   Occasion             111 non-null    object
 6   DressColor           111 non-null    object
 7   DressColor2          111 non-null    object
 8   DressSize            111 non-null    object
 9   DressDesign          111 non-null    object
 10  DressCategory        111 non-null    object
 11  Matching Percentage  111 non-null    int64 
 12  Matching             111 non-null    object
dtypes: int64(2), object(11)
memory usage: 11.4+ KB


In [ ]:
cloth_df.columns

Index(['ImgID', 'BodySize', 'WaistSize', 'Gender', 'Complexion', 'Occasion',
       'DressColor', 'DressColor2', 'DressSize', 'DressDesign',
       'DressCategory', 'Matching Percentage', 'Matching'],
      dtype='object')

In [ ]:
cloth_df.drop('ImgID', inplace=True, axis=1)

In [ ]:
cloth_df.drop('Matching Percentage', inplace=True, axis=1)

In [ ]:
cloth_df.tail()

BodySize  WaistSize Gender Complexion Occasion DressColor DressColor2  \
106       XL         40      F      Asian    Party       Gray        None   
107        M         30      F      Asian    Party      Black        None   
108        M         30      F      Asian   Casual      Green        None   
109        S         24      M      White    Party      Black       Black   
110       XL         36      F      Asian   Casual      White        None   

    DressSize  DressDesign DressCategory Matching  
106         L  Sleeve less      Ethinic         Y  
107         M  Sleeve less      Ethinic         N  
108         M  Sleeve less       Western        N  
109         S  Full Sleeve      Ethinic         Y  
110        XL  Half Sleeve      Ethinic         Y

In [ ]:
cloth_df['BodySize'].value_counts()

M     57
L     26
XL    24
S      4
Name: BodySize, dtype: int64

In [ ]:
cloth_df['WaistSize'].value_counts()

40    31
32    25
36    23
30    18
34    11
24     2
26     1
Name: WaistSize, dtype: int64

In [ ]:
cloth_df['Gender'].value_counts()

F    62
M    49
Name: Gender, dtype: int64

In [ ]:
cloth_df['Complexion'].value_counts()

Asian    83
White    28
Name: Complexion, dtype: int64

In [ ]:
cloth_df['Occasion'].value_counts()

Casual    53
Party     36
Formal    12
Sports    10
Name: Occasion, dtype: int64

In [ ]:
cloth_df['DressColor'].value_counts()

Black     32
Blue      24
White     14
Red        9
Green      8
Gray       7
Pink       6
Orange     4
Yellow     3
violet     2
Golden     1
Silver     1
Name: DressColor, dtype: int64

In [ ]:
cloth_df['DressColor2'].value_counts()

None     93
White    11
Black     4
Green     2
Red       1
Name: DressColor2, dtype: int64

In [ ]:
cloth_df['DressSize'].value_counts()

M     57
L     29
XL    21
S      4
Name: DressSize, dtype: int64

In [ ]:
cloth_df['DressDesign'].value_counts()

Full Sleeve    59
Half Sleeve    36
Sleeve less    16
Name: DressDesign, dtype: int64

In [ ]:
cloth_df['DressCategory'].value_counts()

Western     59
Ethinic     52
Name: DressCategory, dtype: int64

In [ ]:
#pip install category_encoders 

In [ ]:
import category_encoders as ce

In [ ]:
encoder=ce.OrdinalEncoder(cols=['BodySize','Gender','Complexion','Occasion','DressColor','DressColor2','DressSize','DressDesign','DressCategory','Matching'],return_df=True,mapping=[{'col':'BodySize','mapping':{'None':0,'S':1,'M':2,'L':3,'XL':4}},{'col':'Gender','mapping':{'None':0,'M':1,'F':2}},{'col':'Complexion','mapping':{'None':0,'Asian':1,'White':2}},{'col':'Occasion','mapping':{'None':0,'Casual':1,'Party':2,'Formal':3,'Sports':4}},{'col':'DressColor','mapping':{'None':0,'Black':1,'Blue':2,'White':3,'Red':4, 'Green':5,'Gray':6,'Pink':7,'Orange':8,'Yellow':9,'violet':10,'Silver':11,'Golden':12}},{'col':'DressColor2','mapping':{'None':0,'Black':1,'Blue':2,'White':3,'Red':4, 'Green':5,'Gray':6,'Pink':7,'Orange':8,'Yellow':9,'violet':10,'Silver':11,'Golden':12}},{'col':'DressSize','mapping':{'None':0,'S':1,'M':2,'L':3,'XL':4}},{'col':'DressDesign','mapping':{'None':0,'Full Sleeve':1,'Half Sleeve':2,'Sleeve less':3}},{'col':'DressCategory','mapping':{'None':0,'Ethinic':1,'Western':2}},{'col':'Matching','mapping':{'N':0,'Y':1}}])
df_cloth_transformed=encoder.fit_transform(cloth_df)

C:\Users\lipsita\Anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


In [ ]:
df_cloth_transformed.head()

BodySize  WaistSize  Gender  Complexion  Occasion  DressColor  DressColor2  \
0         2         32       2           1         2           8            0   
1         4         40       1           1         2           2            0   
2         2         32       2           1         2           4            0   
3         2         32       2           1         2           4            0   
4         2         32       2           1         2          12            0   

   DressSize  DressDesign  DressCategory  Matching  
0          2            2           -1.0       0.0  
1          4            1           -1.0       1.0  
2          2            2           -1.0       0.0  
3          2            1           -1.0       1.0  
4          2            2           -1.0       1.0

In [ ]:
'''from scipy.stats import zscore

cloth_df_attr = df_cloth_transformed.loc[:, 'BodySize':'DressCategory']  
cloth_df_attr_z = cloth_df_attr.apply(zscore)
  
def replace(x):
    median, std = x.median(), x.std()  
    outliers = (x - median).abs() > 2*std 
    x[outliers] = x.median()       
    return x

cloth_df_corrected = cloth_df_attr_z.apply(lambda x:x.transform(replace))'''

"from scipy.stats import zscore\n\ncloth_df_attr = df_cloth_transformed.loc[:, 'BodySize':'DressCategory']  \ncloth_df_attr_z = cloth_df_attr.apply(zscore)\n  \ndef replace(x):\n    median, std = x.median(), x.std()  \n    outliers = (x - median).abs() > 2*std \n    x[outliers] = x.median()       \n    return x\n\ncloth_df_corrected = cloth_df_attr_z.apply(lambda x:x.transform(replace))"

In [ ]:
array =df_cloth_transformed.values
X = array[:,0:7]
Y = array[:,8]  
test_size = 0.30
seed = 7  
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)
type(X_train)

numpy.ndarray

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
model_score = model.score(X_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_predict))

0.5294117647058824
[[13  3  0]
 [ 6  5  0]
 [ 4  3  0]]


C:\Users\lipsita\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lipsita\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [ ]:
from sklearn import preprocessing
X_train_scaled = preprocessing.scale(X_train)
X_test_scaled = preprocessing.scale(X_test)

In [ ]:
model = LogisticRegression()
model.fit(X_train_scaled, y_train)
y_predict = model.predict(X_test_scaled)
model_score = model.score(X_test_scaled, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_predict))

0.5
[[16  0  0]
 [10  1  0]
 [ 6  1  0]]


C:\Users\lipsita\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lipsita\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
